# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: ${{ matrix.runtime }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        runtime: ["wasmedge"]
    uses: ./.github/workflows/action-fmt.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}
  
  test-image:
    name: ${{ matrix.runtime }}
    strategy:
      matrix:
        runtime: ["common"] # not required, but groups jobs
    uses: ./.github/workflows/action-test-image.yml

  test-image-oci:
    name: ${{ matrix.runtime }}
    strategy:
      matrix:
        runtime: ["common"] # not required, but groups jobs
    uses: ./.github/workflows/action-test-image.yml
    with:
      image: img-oci

  build-ubuntu:
    name: ${{ matrix.runtime }}
    permissions:
      id-token: write
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        runtime: ["wasmedge"]
        libc: ["musl", "gnu"]
        arch: ["x86_64", "aarch64"]
    uses: ./.github/workflows/action-build.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}
      target: "${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}"
      slug: "${{ matrix.arch }}-linux-${{ matrix.libc }}"
      arch: ${{ matrix.arch }}

  smoke-tests:
    name: ${{ matrix.runtime }}
    needs: [build-ubuntu, test-image]
    strategy:
      matrix:
        # 20.04 uses cgroupv1, 22.04 uses cgroupv2
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        runtime: ["wasmedge"]
    uses: ./.github/workflows/action-test-smoke.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}
